services:
  db:
    container_name: security-db
    image: postgres:15.3
    environment:
      POSTGRES_USER: security
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped